Ledneko.WebUI/Areas/Admin/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ledneko.Domain.Abstract;
using Ledneko.Domain.Entities;
using Ledneko.WebUI.Areas.Admin.Models;
using Microsoft.Ajax.Utilities;
using Microsoft.Data.OData;

namespace Ledneko.WebUI.Areas.Admin.Controllers
{
    public class EditController : Controller
    {
        private ISolutionRepository solutions;
        private ICategoryRepository categories;
        private ICatalogRepository catalogs;
        private IServiceRepository services;

        public EditController(ISolutionRepository sln, ICategoryRepository categ, ICatalogRepository catal, IServiceRepository srv)
        {
            solutions = sln;
            categories = categ;
            catalogs = catal;
            services = srv;
        }

        [HttpPost]
        public string DeleteSolution(int solutionId)
        {
            var result = solutions.DeleteSolution(solutionId);

            return result ? "success" : "error occured";
        }

        public ActionResult Solution(int solutionId = -1)
        {
            Solution editItem;
            IQueryable<int> ids = (new int[0]).AsQueryable();
            if (solutionId < 0)
            {
                editItem = new Solution();
                editItem.SolutionViewingDetails = new SolutionViewingDetails();
            }
            else
            {
                editItem = solutions.GetSolutions.FirstOrDefault(sln => sln.Id == solutionId);
                var details = solutions.GetDetails(editItem);
                editItem.SolutionViewingDetails = details;
                ids = solutions.GetScrinshots(details.Id).Select(scrin => scrin.Id);
            }

            var catalogId = solutionId < 0
                ? catalogs.GetCatalogs.First().Id
                : categories.GetCategories.First(categ => categ.Id == editItem.CategoryId).CatalogId;

            var result = new EditSolutionModel
            {
                Solution = editItem,
                Catalogs = catalogs.GetCatalogs,
                Categories = categories.GetCategories.Where(categ => categ.CatalogId == catalogId),
                CurrentCategory = editItem.CategoryId,
                CurentCatalog = catalogId,
                Ids = ids
            };


            return View(result);
        }

        [HttpPost]
        public RedirectToRouteResult SaveLogo(int solutionId, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var DataImageBytes = new byte[image.ContentLength];
                image.InputStream.Read(DataImageBytes, 0, image.ContentLength);

                if (solutions.SaveLogo(solutionId, image.ContentType, DataImageBytes))
                    TempData["message"] = string.Format("\"Логотип\" был сохранен в Базе Данных");
                else
                    TempData["message"] = string.Format("Не удалось сохранить \"логотип\" в Базе Данных");
            }

            return RedirectToAction("Solution", new { solutionId = solutionId });
        }

        [HttpPost]
        public string AddScrinshot(int detailsId, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var DataImageBytes = new byte[image.ContentLength];
                image.InputStream.Read(DataImageBytes, 0, image.ContentLength);

                if (solutions.SaveScrin(detailsId, image.ContentType, DataImageBytes))
                    return solutions.GetScrinshots(detailsId).OrderByDescending(scrin => scrin.Id).FirstOrDefault().Id.ToString();
            }
            return "error occured";
        }

        [HttpPost]
        public string DeleteScrinshot(int scrinId, int detailsId)
        {
            if (solutions.DeleteScrin(detailsId, scrinId))
                return "success";
            else
                return "error occured";
        }

        [HttpPost]
        public ActionResult Solution(EditedSolutionModel inputParams)
        {
            var sln = new Solution
            {
                Id = inputParams.SolutionId,
                CategoryId = inputParams.CategoryId,
                DemoUrl = inputParams.DemoUrl,
                Name = inputParams.Name,
                Price = inputParams.Price,
                OldPrice = inputParams.OldPrice,
                SolutionViewingDetailsId = inputParams.ViewingDetailsId
            };

            var details = new SolutionViewingDetails
            {
                Id = inputParams.ViewingDetailsId,
                Header = inputParams.Header,
                Description = inputParams.Description
            };

            if (!ModelState.IsValid || !solutions.SaveSolution(sln, details))
            {
                sln.SolutionViewingDetails = details;
                var model = new EditSolutionModel
                {

                };
                return View(model);
            }

            return RedirectToAction("Solutions", "List");
        }


        public ActionResult Category(int catid = 0)
        {
            Category category;
            if (catid == 0)
                category = new Category();
            else
            {
                category = categories.GetCategories.FirstOrDefault(cat => cat.Id == catid);
            }

            if (category == null)
                return RedirectToAction("Categories", "List");
            EditCategoryModel editCategoryModel = new EditCategoryModel
            {
                Category = category,
                Catalogs = catalogs.GetCatalogs
            };

            return View(editCategoryModel);
        }

        [HttpPost]
        public string DeleteCategory(int catid = 0)
        {
            var result = categories.DeleteCategory(catid);

            return result ? "success" : "error occured";
        }

        [HttpPost]
        public ActionResult SaveCategory(Category cat)
        {
            categories.SaveCategory(cat);


            return RedirectToAction("Categories", "List");
        }

        public ActionResult Catalog(int catid = 0)
        {
            Catalog catalog;
            if (catid == 0)
                catalog = new Catalog();
            else
            {
                catalog = catalogs.GetCatalogs.FirstOrDefault(cat => cat.Id == catid);
            }

            if (catalog == null)
                return RedirectToAction("Catalogs", "List");

            return View(catalog);
        }

        [HttpPost]
        public string DeleteCatalog(int catid = 0)
        {
            var result = catalogs.DeleteCatalog(catid);

            return result ? "success" : "error occured";
        }

        [HttpPost]
        public ActionResult SaveCatalog(Catalog cat)
        {
            catalogs.SaveCatalog(cat);


            return RedirectToAction("Catalogs", "List");
        }
        public ActionResult Service(int srvid = 0)
        {
            Service service;
            if (srvid == 0)
                service = new Service();
            else
            {
                service = services.GetServices.FirstOrDefault(srv => srv.Id == srvid);
            }

            if (service == null)
                return RedirectToAction("Services", "List");

            var result = new EditServiceModel
            {
                Service = service,
                Images = services.GetPictures.Where(pic => pic.ServiceId == service.Id).Select(pic => pic.Id)
            };

            return View(result);
        }

        [HttpPost]
        public string DeleteService(int srvid = 0)
        {
            var result = services.DeleteService(srvid);

            return result ? "success" : "error occured";
        }

        [ValidateInput(false)] 
        [HttpPost]
        public ActionResult SaveService(Service service)
        {
            services.SaveService(service);

            return RedirectToAction("Services", "List");
        }

        [HttpPost]
        public ActionResult SaveSrvLogo(int srvId, HttpPostedFileBase image)
        {
            if (image != null)
            {
                var DataImageBytes = new byte[image.ContentLength];
                image.InputStream.Read(DataImageBytes, 0, image.ContentLength);

                if (services.SaveLogo(srvId, DataImageBytes, image.ContentType))
                    TempData["message"] = string.Format("\"Логотип\" был сохранен в Базе Данных");
                else
                    TempData["message"] = string.Format("Не удалось сохранить \"логотип\" в Базе Данных");
            }

            return RedirectToAction("Service", new { srvid = srvId });
        }

        [HttpPost]
        public string SavePicture(int srvId, HttpPostedFileBase image)
        {
            if (image != null)
            {

                var pic = new Picture();
                pic.ServiceId = srvId;

                var DataImageBytes = new byte[image.ContentLength];
                image.InputStream.Read(DataImageBytes, 0, image.ContentLength);

                pic.ImageData = DataImageBytes;
                pic.MimeType = image.ContentType;

                if (services.SavePicture(pic))
                    return pic.Id.ToString();
            }

            return "error occured";

        }


        [HttpPost]
        public string DeletePicture(int picId)
        {
            if (services.DeletePicture(picId))
                return "success";
            else
                return "error occured";
        }

    }
}

Ledneko.WebUI/Areas/Admin/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ledneko.Domain.Abstract;
using Ledneko.Domain.Entities;

namespace Ledneko.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    public class ListController : Controller
    {
        private ISolutionRepository solutions;
        private ICategoryRepository categories;
        private ICatalogRepository catalogs;
        private IServiceRepository services;

        private readonly int itemsPerPage = 10;

        public ListController(ISolutionRepository sln, ICategoryRepository categ, ICatalogRepository catal, IServiceRepository srv)
        {
            solutions = sln;
            categories = categ;
            catalogs = catal;
            services = srv;
        }

        public ActionResult Menu(string currentTab)
        {
            return View((object)currentTab);
        }

        public ActionResult Solutions(int page = 1, string name = null)
        {
            IQueryable<object> collection = solutions.GetSolutions.Join(categories.GetCategories, sln => sln.CategoryId, cat => cat.Id, (sln, cat) => new
            {
                Id = sln.Id,
                Name = sln.Name,
                Category = cat,
                Price = sln.Price,
                OldPrice = sln.OldPrice,
                DataImageBytes = sln.DataImageBytes,
                DemoUrl = sln.DemoUrl,
                MimeType = sln.MimeType,
                SolutionViewingDetailsId = sln.SolutionViewingDetailsId
            }).Where(sln => name == null || sln.Name.Contains(name)).OrderBy(sln => sln.Id).Skip((page - 1) * itemsPerPage).Take(itemsPerPage);
            return View(collection);
        }

        public ActionResult Categories(int page = 1, string name = null)
        {
            IQueryable<object> collection = categories.GetCategories.Join(catalogs.GetCatalogs, category => category.CatalogId, catalog => catalog.Id, (category, catalog) => new
            {
                Id = category.Id,
                Name = category.Name,
                CatalogName = catalog.Name
            }).Where(cat => name == null || cat.Name.Contains(name)).OrderBy(cat => cat.Id).Skip((page - 1) * itemsPerPage).Take(itemsPerPage);
            return View(collection);
        }


        public ActionResult Catalogs(int page = 1, string name = null)
        {
            var collection = catalogs.GetCatalogs.Where(cat => name == null || cat.Name.Contains(name)).OrderBy(cat => cat.Id).Skip((page - 1) * itemsPerPage).Take(itemsPerPage);

            return View(collection);
        }

        public ActionResult Services(int page = 1, string name = null)
        {
            var collection = services.GetServices.Where(serv => name == null || serv.Name.Contains(name)).OrderBy(serv => serv.Id).Skip((page - 1) * itemsPerPage).Take(itemsPerPage);

            return View(collection); 
        }

    }
}

Ledneko.WebUI/Areas/Admin/Views/List/Catalogs.cshtml
@using System.Net.Mime
@model IQueryable<Ledneko.Domain.Entities.Catalog>

@{
    ViewBag.Title = "Просмотр каталогов";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.CurrentTab = "Catalogs";
    const int descLength = 50;
}

<h2>Список каталогов</h2>

@if (Model == null)
{
    <h1 class="text-muted">Пусто</h1>
}
else
{
<table>
    <thead>
        <th>Название</th>
        <th>Краткое описание</th>
        <th>Редактировать строку</th>
    </thead>
    <tbody>
        @foreach (var cat in Model)
        {
            <tr>
               
                 <td>@cat.Name</td>
                <td>@(cat.Description != null ? cat.Description.Substring(0, cat.Description.Length > descLength ? descLength : cat.Description.Length) +".." : "Пусто")</td>
                <td>
                    @Html.ActionLink("редактировать", "Catalog", "Edit", new{catid=cat.Id},
                        new{@class="btn btn-success"})
                    <button class="btn btn-danger" data-catid="@cat.Id">удалить</button>
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
<script type="text/javascript">
    $('tbody').on('click', function (event) {
        var buttonElement = event.target;
        var catid = buttonElement.dataset['catid'];
        console.log("clicked");
        $.ajax({
            method: "POST",
            url: '@Url.Action("DeleteCatalog", "Edit")',
            data: { catid: catid }

        }).done(function (msg) {
            var rowElement = buttonElement.parentNode.parentNode;
            rowElement.parentNode.removeChild(rowElement);
        });
    });
</script>
}
}

Ledneko.WebUI/Areas/Admin/Views/List/Categories.cshtml
@using Ledneko.Domain.Entities;
@using Microsoft.Ajax.Utilities
@model IQueryable<object>

@{
    ViewBag.Title = "Просмотр категорий";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.CurrentTab = "Categories";
}

<h2>Список решений</h2>
@if (Model == null)
{
    <h1 class="text-muted">Пусто</h1>
}
else
{
<table>
    <thead>
        <th>Название</th>
        <th>Каталог</th>
        <th>Редактировать строку</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            
            var cat = item.GetType();
           
            <tr>
               
                 <td>@cat.GetProperty("Name").GetValue(item)</td>
                <td>@cat.GetProperty("CatalogName").GetValue(item)</td>
                <td>
                    @Html.ActionLink("редактировать", "Category", "Edit", new{catid=cat.GetProperty("Id").GetValue(item)},
                        new{@class="btn btn-success"})
                    <button class="btn btn-danger" data-catid="@cat.GetProperty("Id").GetValue(item)">удалить</button>
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
<script type="text/javascript">
    $('tbody').on('click', function (event) {
        var buttonElement = event.target;
        var catid = buttonElement.dataset['catid'];
        console.log("clicked");
        $.ajax({
            method: "POST",
            url: '@Url.Action("DeleteCategory", "Edit")',
            data: { catid: catid }

        }).done(function (msg) {
            var rowElement = buttonElement.parentNode.parentNode;
            rowElement.parentNode.removeChild(rowElement);
        });
    });
</script>
}
}

Ledneko.WebUI/Areas/Admin/Views/List/Menu.cshtml
@model String

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" 
            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img style="max-height: 40pt; max-width: 30pt;" src="/Content/adm_logo.jpg"/>
    </div>
      
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li @if (Model == "Solutions"){<text>class="active"</text>}>
              <a href="@Url.Action("Solutions", "List")">Список решений</a>
          </li>
          <li @if (Model == "Categories")
              {<text>class="active"</text>}>
              <a href="@Url.Action("Categories", "List")">Список категорий</a>
          </li>
          <li @if (Model == "Catalogs")
              {<text>class="active"</text>}>
              <a href="@Url.Action("Catalogs", "List")">Список каталогов</a>
          </li>
          <li @if (Model == "Services")
              {<text>class="active"</text>}>
              <a href="@Url.Action("Services", "List")">Список услуг</a>
          </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Добавить <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="@Url.Action("Solution", "Edit")">новое решение</a></li>
            <li><a href="@Url.Action("Category", "Edit")">новая категория</a></li>
            <li><a href="@Url.Action("Catalog", "Edit")">новый каталог</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="@Url.Action("Service", "Edit")">новая услуга</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Ввести цены</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" name="Name" placeholder="Введите название">
        </div>
        <button type="submit" class="btn btn-default">Поиск</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Ledneko.WebUI/Areas/Admin/Views/List/Services.cshtml
@model IQueryable<Ledneko.Domain.Entities.Service>

@{
    ViewBag.Title = "Услуги";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.CurrentTab = "Services";
    const int descLength = 50;
}

<h2>Список услуг</h2>

@if (Model == null)
{
    <h1 class="text-muted">Пусто</h1>
}
else
{
    <table>
        <thead>
            <th>Название</th>
            <th>Краткое описание</th>
            <th>Редактировать строку</th>
        </thead>
        <tbody>
            @foreach (var serv in Model)
            {
                <tr>

                    <td>@serv.Name</td>
                    <td>@(serv.Description != null ? serv.Description.Substring(0, serv.Description.Length > descLength ? descLength : serv.Description.Length) + ".." : "Пусто")</td>
                    <td>
                        @Html.ActionLink("редактировать", "Service", "Edit", new { srvid = serv.Id },
                        new { @class = "btn btn-success" })
                        <button class="btn btn-danger" data-srvid="@serv.Id">удалить</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @section scripts {
        <script type="text/javascript">
            $('tbody').on('click', function (event) {
                var buttonElement = event.target;
                var srvid = buttonElement.dataset['srvid'];
                if (!srvid)
                    return;
                console.log("clicked");
                $.ajax({
                    method: "POST",
                    url: '@Url.Action("DeleteService", "Edit")',
            data: { srvid: srvid }

        }).done(function (msg) {
            var rowElement = buttonElement.parentNode.parentNode;
            rowElement.parentNode.removeChild(rowElement);
        });
    });
        </script>
    }
}

Ledneko.WebUI/Areas/Admin/Views/List/Solutions.cshtml
@using Ledneko.Domain.Entities;
@using Microsoft.Ajax.Utilities
@model IQueryable<object>

@{
    ViewBag.Title = "Просмотр решений";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.CurrentTab = "Solutions";
}

<h2>Список решений</h2>
@if (Model == null)
{
    <h1 class="text-muted">Пусто</h1>
}
else
{
<table>
    <thead>
        <th>Описание</th>
        <th>Цeна</th>
        <th>Категория</th>
        <th>Редактировать строку</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            
            var sln = item.GetType();
            var c=((Category) sln.GetProperty("Category").GetValue(item));
           
            <tr>
               
                 <td>@sln.GetProperty("Name").GetValue(item)</td>
                <td>@sln.GetProperty("Price").GetValue(item)</td>
                <td>@c.Name</td>
                <td>
                    @Html.ActionLink("редактировать", "Solution", "Edit", new{solutionId=sln.GetProperty("Id").GetValue(item)},
                        new{@class="btn btn-success"})
                    <button class="btn btn-danger" data-solutionid="@sln.GetProperty("Id").GetValue(item)">удалить</button>
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
<script type="text/javascript">
    $('tbody').on('click', function (event) {
        var buttonElement = event.target;
        var solutionid = buttonElement.dataset['solutionid'];
        console.log("clicked");
        $.ajax({
            method: "POST",
            url: '@Url.Action("DeleteSolution", "Edit")',
            data: { solutionId: solutionid }

        }).done(function (msg) {
            var rowElement = buttonElement.parentNode.parentNode;
            rowElement.parentNode.removeChild(rowElement);
        });
    });
</script>
}
}